//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.03 at 12:40:03 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mx.hush.core.models;
